### ISSUE TITLE
Melhorias do Hotbit preto

### ISSUE THREAD

**Issue by sdsnatcher** [Danjovic/MSX#1]
O Hotbit preto tem diversas melhorias em relação ao branco, que não estão mostradas no esquemático:

- Capacitor de acoplamento na saída de audio
- Alterações nos valores dos resistores do mixer de áudio
- Melhoras na placa analógica:
1. Correção das cores
2. Chave de seleção da intensidade do filtro de luma
3. Adição do pino de clock ao conector que vai ligado à placa mãe

**Comment by Danjovic** [comment]
> 
> 
> O Hotbit preto tem diversas melhorias em relação ao branco, que não estão mostradas no esquemático:
> 
>     * Capacitor de acoplamento na saída de audio
> 
>     * Alterações nos valores dos resistores do mixer de áudio
> 
>     * Melhoras na placa analógica:
> 
> 
>     1. Correção das cores
> 
>     2. Chave de seleção da intensidade do filtro de luma
> 
>     3. Adição do pino de clock ao conector que vai ligado à placa mãe

Estas alterações constam de algum diagrama/manual de serviço disponível?

**Comment by fbelavenuto** [comment]
Danjovic, eu fiz um levantamento da placa analógica do Hotbit preto com ajuda do Corel Draw e usei o seu esquema como base para reproduzir as mudanças. Os nomes dos componentes mudaram bastante!
Segue link com os arquivos para auxiliar na parte da analógica:
https://drive.google.com/file/d/16L6AgCOuCNuPQpng5gtxPSt97xELAhRt/view?usp=sharing

**Comment by Danjovic** [comment]
Bom dia Fábio!
Obrigado pelas informações. Vou atualizar e subir o esquema pro Github.

No mais tudo certo por ai?

Abraço,
Daniel
________________________________
De: Fabio Belavenuto <notifications@github.com>
Enviado: segunda-feira, 28 de dezembro de 2020 00:10
Para: Danjovic/MSX <MSX@noreply.github.com>
Cc: Danjovic <danjovic@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [Danjovic/MSX] Melhorias do Hotbit preto (#1)


Danjovic, eu fiz um levantamento da placa analógica do Hotbit preto com ajuda do Corel Draw e usei o seu esquema como base para reproduzir as mudanças. Os nomes dos componentes mudaram bastante!
Segue link com os arquivos para auxiliar na parte da analógica:
https://drive.google.com/file/d/16L6AgCOuCNuPQpng5gtxPSt97xELAhRt/view?usp=sharing

**Comment by fbelavenuto** [comment]
> Bom dia Fábio! Obrigado pelas informações. Vou atualizar e subir o esquema pro Github. No mais tudo certo por ai? Abraço, Daniel
> […](#)

Sim, td certo!
